[package]
name = "tank_wars_server"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.7"

tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread", "fs"] }
futures = { default-features = false, version = "0.3.21" }

tracing = "0.1.34"
tracing-subscriber = "0.3.11"

quinn = "0.8.2"
local-ip-address = "0.4.4"

rcgen = "0.9.2"
rustls = { default-features = false, version = "0.20.4" }

color-eyre = "0.6.1"

directories-next = "2.0.0"

rmp-serde = "1.1.0"
serde = { version = "1.0.136", features = ["derive"] }

dashmap = "5.2.0"

lazy_static = "1.4.0"

sea-orm = { version = "0.7.1", features = ["sqlx-postgres", "runtime-tokio-rustls"]}

chrono = "0.4.19"

[profile.release]
strip = true